# Generated by Django 5.1.6 on 2025-02-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcomanda',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
