# Generated by Django 5.1.6 on 2025-02-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0003_alter_produto_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
